branch-defaults:
  master:
    environment: NewWebApp2-env
    group_suffix: null
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: NewWebApp2
  branch: null
  default_ec2_keyname: FinalJenkins
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
